# Generated by Django 2.1 on 2019-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Moscow', max_length=50, verbose_name='Город'),
        ),
    ]
