# Generated by Django 2.1 on 2019-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('1', 'Moscow'), ('2', 'Piter')], default='Moscow', max_length=50, verbose_name='Город'),
        ),
    ]
