# Generated by Django 2.1 on 2019-08-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190818_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('1', 'Russia'), ('2', 'Usa'), ('3', 'Ukraine'), ('4', 'Belarus')], default='Russia', max_length=120, verbose_name='Страна'),
        ),
    ]
