# Generated by Django 2.1 on 2019-08-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('1', 'Washington'), ('2', 'Florida'), ('3', 'Texas')], default='California', max_length=120, verbose_name='Штат'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('1', 'Moscow'), ('2', 'St.Petersburg'), ('3', 'San-Francisco'), ('4', 'Boston'), ('5', 'Prague')], default='Moscow', max_length=50, verbose_name='Город'),
        ),
    ]
