# Generated by Django 2.2.2 on 2019-06-27 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 16, 11, 31, 173550, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
