# Generated by Django 2.2.2 on 2019-06-27 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190627_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 16, 29, 26, 308009, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(to='photologue.Gallery', verbose_name='Галерея'),
        ),
    ]
