# Generated by Django 2.1 on 2019-09-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
